name=GS32BIOS
version=1.1.0
author=pimnik98
maintainer=GS32Bios
sentence=A highly customizable, pseudo-graphical terminal BIOS interface for ESP32.
paragraph=An elegant ANSI/VT100 terminal BIOS style control panel designed for ESP32 microcontrollers. It features multi-tab navigation, nested submenus, action callbacks, system status monitoring (CPU model, heap RAM, uptime), and interactive input popups for numeric, boolean, dropdown select lists, and text variables. Perfect for CLI interfaces and serial console configuration.
category=Display
url=https://github.com/GS32Bios/GS32Bios
architectures=esp32
includes=GS32BIOS.h
